# Generated by Django 5.1 on 2025-03-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='date_two',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
