# Generated by Django 5.1 on 2025-03-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_newsarticle_date_two_alter_newsarticle_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=5000),
        ),
    ]
