# Generated by Django 5.1 on 2025-03-07 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_alter_newsarticle_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='date_two',
        ),
    ]
